name = "Abyssus Infinitum"
author = "glomdom"
version = "0.0.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfbde6b9839a6517849da7f031bf2f8cf7a448737b98e7ac31dec4f5d7a5c2b8"

[versions]
forge = "43.3.8"
minecraft = "1.19.2"
