name = "Abyssus Infinitum"
author = "glomdom"
version = "0.0.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8e8b07380977947c1225aa267513ac2083b59fa32901fa5c441629ff16abebe"

[versions]
forge = "43.3.8"
minecraft = "1.19.2"
