name = "Abyssus Infinitum"
author = "glomdom"
version = "0.0.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d59f41e0e8e882d1b4466a08a77c0e45c4c43b14d0c12e742221c91c733d68ef"

[versions]
forge = "43.3.8"
minecraft = "1.19.2"
