name = "Abyssus Infinitum"
author = "glomdom"
version = "0.0.0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "888b1e3c014281589666334f3b55fe5d541ae55fbc32083eb12d0bccd7140827"

[versions]
forge = "43.3.8"
minecraft = "1.19.2"
